#! /bin/bash

set -e

REFFILE=$1
BAMFILE=$2
OUTFILE=$3

VCFFILE=/tmp/calls.vcf.gz
NORMFILE=/tmp/calls.norm.bcf
FLTINDELSFILE=/tmp/calls.norm.flt-indels.bcf

bcftools mpileup -Ou -f $REFFILE $BAMFILE | bcftools call -mv -Oz -o $VCFFILE
bcftools index $VCFFILE
bcftools norm -f $REFFILE $VCFFILE -Ob -o $NORMFILE
bcftools filter --IndelGap 5 $NORMFILE -Ob -o $FLTINDELSFILE

cat $REFFILE | bcftools consensus $VCFFILE > $OUTFILE
