#! /bin/bash

set -e

SAMDIR=$1
OUTDIR=$2

mkdir -p $OUTDIR

for file in `ls $SAMDIR/*.sam $SAMDIR/*.bam 2>/dev/null`; do
    fq=$OUTDIR/`basename ${file%.[sb]am}.fastq.gz`
    echo $file
    samtools fastq $file -o $fq
done
